<?php

/**
 * @file
 * Increases flexibility during query/analysis operations by indexing Fedora XML content within a read-only XML Database.  This module connects Islandora/Fedora to an XML database to allow advanced XQuery 3.0 with full-text query execution on Fedora XML content to help power advanced queries for analysis purposes.
 *
 * = provide an list of APIs for advance queries to the XML database  
 */

/**
 * Implements hook_menu().
 */
function islandora_cwrc_basexdb_menu() {
  return array(
    'admin/islandora/tools/islandora_cwrc_basex' => array(
      'title' => 'XML Database Module',
      'description' => 'Configure the BaseX database module.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_cwrc_basexdb_admin_settings_form'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    )
  );
}



